---
version: '3.8'
services:
  weaviate:
    container_name: weaviate-db
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.22.7
    ports:
      - 18080:8080
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
  app:
    init: true
    container_name: chat-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_URL=http://weaviate:8080
      - RECORD_MANAGER_DB_URL=sqlite:///db/test.db
    volumes:
      - .:/app
    depends_on:
      - weaviate
    # to connect to ollama running on host at
    # available at http://host.docker.internal:11434
    extra_hosts:
      host.docker.internal: host-gateway
    # command: bash -c "echo Running... && sleep inf"
    command: bash -c "poetry run make start"

volumes:
  weaviate_data:
