---
version: '3.8'
services:
  app:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - .:/app
      - torch_cache:/root/.cache/torch
    extra_hosts:
      host.docker.internal: host-gateway
    command: sleep inf

volumes:
  torch_cache:
